// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationeryStore.Mvc.Data;

#nullable disable

namespace StationeryStore.Mvc.Migrations
{
    [DbContext(typeof(StationeryDbContext))]
    [Migration("20260620052950_AddAuditSoftDeleteRowVersio")]
    partial class AddAuditSoftDeleteRowVersio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StationeryStore.Mvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bút viết"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sổ - vở"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dụng cụ học tập"
                        });
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.InventoryDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryRecordId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StationeryItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryRecordId");

                    b.HasIndex("StationeryItemId");

                    b.ToTable("InventoryDetails", (string)null);
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.InventoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InventoryRecords", (string)null);
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.StationeryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("StationeryItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Thiên Long",
                            CategoryId = 1,
                            Code = "SP001",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bút bi màu xanh, viết trơn.",
                            ImageUrl = "/images/pen.jpg",
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 20,
                            Name = "Bút bi Thiên Long",
                            Price = 5000m,
                            StockQuantity = 100,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Hồng Hà",
                            CategoryId = 2,
                            Code = "SP002",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sổ tay 200 trang.",
                            ImageUrl = "/images/notebook.jpg",
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 10,
                            Name = "Sổ tay Hồng Hà",
                            Price = 25000m,
                            StockQuantity = 50,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "FlexOffice",
                            CategoryId = 3,
                            Code = "SP003",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thước nhựa trong suốt 30cm.",
                            ImageUrl = "/images/ruler.jpg",
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 15,
                            Name = "Thước kẻ 30cm",
                            Price = 8000m,
                            StockQuantity = 70,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Deli",
                            CategoryId = 3,
                            Code = "SP004",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hộp bút vải dùng cho học sinh.",
                            ImageUrl = "/images/pencilbox.jpg",
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 30,
                            Name = "Hộp bút vải",
                            Price = 55000m,
                            StockQuantity = 20,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            Brand = "FlexOffice",
                            CategoryId = 3,
                            Code = "SP005",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gôm tẩy mềm, không làm rách giấy.",
                            ImageUrl = "/images/eraser.jpg",
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 40,
                            Name = "Gôm tẩy học sinh",
                            Price = 3000m,
                            StockQuantity = 150,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Hồng Hà",
                            CategoryId = 2,
                            Code = "SP006",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tập học sinh 200 trang.",
                            ImageUrl = "/images/notebook200.jpg",
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 15,
                            Name = "Tập học sinh 200 trang",
                            Price = 35000m,
                            StockQuantity = 60,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Deli",
                            CategoryId = 1,
                            Code = "SP007",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bút chì màu 24 cây.",
                            ImageUrl = "/images/pencilcolor.jpg",
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 15,
                            Name = "Bút chì màu Deli",
                            Price = 65000m,
                            StockQuantity = 5,
                            SupplierId = 4
                        });
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thiên Long",
                            Phone = "0901234567"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hồng Hà",
                            Phone = "0907654321"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FlexOffice",
                            Phone = "0901122334"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deli",
                            Phone = "0901567234"
                        });
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.InventoryDetail", b =>
                {
                    b.HasOne("StationeryStore.Mvc.Models.InventoryRecord", "InventoryRecord")
                        .WithMany("InventoryDetails")
                        .HasForeignKey("InventoryRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationeryStore.Mvc.Models.StationeryItem", "StationeryItem")
                        .WithMany()
                        .HasForeignKey("StationeryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryRecord");

                    b.Navigation("StationeryItem");
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.StationeryItem", b =>
                {
                    b.HasOne("StationeryStore.Mvc.Models.Category", "Category")
                        .WithMany("StationeryItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StationeryStore.Mvc.Models.Supplier", "Supplier")
                        .WithMany("StationeryItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.Category", b =>
                {
                    b.Navigation("StationeryItems");
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.InventoryRecord", b =>
                {
                    b.Navigation("InventoryDetails");
                });

            modelBuilder.Entity("StationeryStore.Mvc.Models.Supplier", b =>
                {
                    b.Navigation("StationeryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
